version: 0.2

phases:
  install:
    commands:
      - echo Install phase...
      - cd wowup-electron
      - npm i
  build:
    commands:
      - echo Build phase...
      - npm run electron:publish:never